=== NCIP/c3pr/codebase/projects/grid/C3PRStudyConsumer/schema/C3PRStudyConsumer/c3pr-domain.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="gme://c3pr.cabig/2.0/edu.duke.cabig.c3pr.domain"
           xmlns="gme://c3pr.cabig/2.0/edu.duke.cabig.c3pr.domain" elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation xml:lang="en">
            Registartion schema, referring c3prV2-I2.EAP
        </xs:documentation>
    </xs:annotation>

    <xs:element name="registration" type="Registration"/>



    <xs:complexType name="Registration">
        <xs:sequence>
            <xs:element name="informedConsentFormSignedDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="studyParticipantIdentifier" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="eligibilityIndicator" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="participant"  type="ParticipantType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="study"  type="Study" minOccurs="0" maxOccurs="1"/>
            <xs:element name="identifier"  type="IdentifierType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="healthCareSiteGridId" type="xs:string"/>
        <xs:attribute name="studyGridId" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ParticipantType">
        <xs:sequence>
            <xs:element name="firstName"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="lastName"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="address"  type="AddressType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="administrativeGenderCode"   type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="birthDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
            <xs:element name="ethnicGroupCode"   type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="maritalStatusCode"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="raceCode"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="identifier"  type="IdentifierType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="IdentifierType">
        <xs:sequence>
            <xs:element name="source"   type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="value"   type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="isprimary"  type="xs:boolean" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="streetAddress" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="city" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="stateCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="postalCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="countryCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="study" type="Study"/>

    <xs:complexType name="Study">
        <xs:sequence>
            <xs:element name="blindedIndicator" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="multiInstitutionIndicator" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="randomizedIndicator" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="shortTitleText" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="longTitleText"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="descriptionText"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="precisText"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="phaseCode"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="sponsorCode"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="status"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="type"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="primaryIdentifier"  type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="targetAccrualNumber"  type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="epoch"  type="EpochType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="studySite"  type="StudySiteType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="identifier"  type="IdentifierType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="incCriteria"  type="EligibilityCriteriaType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="excCriteria"  type="EligibilityCriteriaType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="stratificationCriteria"  type="StratificationCriterionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="EpochType">
        <xs:sequence>
            <xs:element name="arm" type="ArmType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="descriptionText" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ArmType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="descriptionText" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="targetAccrualNumber" type="xs:int" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="StudySiteType">
        <xs:sequence>
            <xs:element name="irbApprovalDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
            <xs:element name="roleCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="startDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
            <xs:element name="statusCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="endDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
            <xs:element name="site" type="HealthcareSiteType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="HealthcareSiteType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="descriptionText" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="address" type="AddressType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="trimmedName" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="nciInstituteCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="StratificationCriterionType">
        <xs:sequence>
            <xs:element name="questionNumber" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="questionText" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="permissibleAnswer" type="StratificationCriterionPermissibleAnswerType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="StratificationCriterionPermissibleAnswerType">
        <xs:sequence>
            <xs:element name="permissibleAnswer" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EligibilityCriteriaType">
        <xs:sequence>
            <xs:element name="notApplicableIndicator" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="questionNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="questionText" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="gridId" type="xs:string"/>
    </xs:complexType>


</xs:schema>

=== NCIP/c3pr/codebase/projects/grid/RegistrationConsumerImpl/test/resources/SampleRegistrationMessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<registration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="gme://c3pr.cabig/2.0/edu.duke.cabig.c3pr.domain ../../../../core/resources/xsd/c3pr-domain.xsd"
    xmlns="gme://c3pr.cabig/2.0/edu.duke.cabig.c3pr.domain">
    <studySite>
        <healthcareSite gridId="siteGridId"/>
        <irbApprovalDate>2007-09-25</irbApprovalDate>
        <startDate>2007-09-25</startDate>
    </studySite>
    <studyRef gridId="testStudyGridId"> </studyRef>
    <participant xmlns:ns1="gme://c3pr.cabig/2.0/edu.duke.cabig.c3pr.domain">
        <ns1:firstName>tempStr</ns1:firstName>
        <ns1:lastName>tempStr</ns1:lastName>
        <ns1:address>
            <ns1:streetAddress>12359 Sunrise Valley Dr</ns1:streetAddress>
            <ns1:city>Reston</ns1:city>
            <ns1:stateCode>VA</ns1:stateCode>
            <ns1:postalCode>20191</ns1:postalCode>
            <ns1:countryCode>USA</ns1:countryCode>
        </ns1:address>
        <ns1:administrativeGenderCode>tempStr</ns1:administrativeGenderCode>
        <ns1:birthDate>2009-01-20</ns1:birthDate>
        <ns1:ethnicGroupCode>tempStr</ns1:ethnicGroupCode>
        <ns1:maritalStatusCode>tempStr</ns1:maritalStatusCode>
        <ns1:raceCode>tempStr</ns1:raceCode>    
        <ns1:identifier xsi:type="SystemAssignedIdentifierType">
            <ns1:source>asd</ns1:source>
            </ns1:identifier>
    </participant>
   
    <startDate>2009-01-20</startDate>
    <informedConsentFormSignedDate>2009-01-20</informedConsentFormSignedDate>

    <regDataEntryStatus>INCOMPLETE</regDataEntryStatus>
    <regWorkflowStatus>UNREGISTERED</regWorkflowStatus>
</registration>
